"""add agents and stats tables

Revision ID: 2e42d9590952
Revises: 
Create Date: 2025-07-16 17:34:23.503077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e42d9590952'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('title', sa.String(), nullable=True))
    op.add_column('agents', sa.Column('avatar', sa.String(), nullable=True))
    op.add_column('agents', sa.Column('languages', sa.JSON(), nullable=True))
    op.add_column('agents', sa.Column('certifications', sa.JSON(), nullable=True))
    op.add_column('agents', sa.Column('achievements', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'achievements')
    op.drop_column('agents', 'certifications')
    op.drop_column('agents', 'languages')
    op.drop_column('agents', 'avatar')
    op.drop_column('agents', 'title')
    # ### end Alembic commands ###
